# Jekyll Configuration
# --------------------

name: papitas
url: https://merunga.github.io/papitas
safe: false
markdown: kramdown
highlighter: pygments

source: ./src
destination: ./dist

keep_files: [ 'assets' ]

permalink: /:year/:month/:day/:title

exclude: [node_modules, bower_components, src/_styles, app]
