papas = [
  {
    "numero":1,
    "nombre":"ALLQA COMPIS",
    "nombreAlternativo":"Alqa Imilla",
    "significadoNombre":"Papa de 2 colores rosado y blanco",
    "colorFlor":"Violeta",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"0:00",
    "audioFin":"0:02"
  },
  {
    "numero":2,
    "nombre":"ALLQA PALTA",
    "nombreAlternativo":"Wanka Lliqlla",
    "significadoNombre":"Aplanado bicolor- Manta de wanka",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Blanco a crema",
    "formaRara":"Aplanado",
    "toleranciaHelada":"Fuerte",
    "usoCocina":"Watia, hervido y sopa",
    "lugar":"Huancavelica",
    "audioIni":"0:05",
    "audioFin":"0:07"
  },
  {
    "numero":3,
    "nombre":"ALLQA WALASH",
    "nombreAlternativo":"Walash",
    "significadoNombre":"Joven bicolor",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Amarillo",
    "formaRara":"Oblongo",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"0:11",
    "audioFin":"0:13"
  },
  {
    "numero":4,
    "nombre":"AMPAIRAS",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Ampairas, Amparaes (pueblo)",
    "colorFlor":"Blanco",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco",
    "formaRara":"No tiene",
    "toleranciaHelada":"Débil",
    "usoCocina":"Hervido, sopas",
    "lugar":"Cusco",
    "audioIni":"0:16",
    "audioFin":"0:19"
  },
  {
    "numero":5,
    "nombre":"AQU SUYTU",
    "nombreAlternativo":"Yuraq Suytu",
    "significadoNombre":"Arenoso Largo",
    "colorFlor":"Rosado a rojo",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco o crema",
    "formaRara":"Oblongo alargado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Huancavelica",
    "audioIni":"0:23",
    "audioFin":"0:26"
  },
  {
    "numero":6,
    "nombre":"AZUL ÑAWI PASÑA",
    "nombreAlternativo":"Yana Chusña",
    "significadoNombre":"Muchacha con ojos azules",
    "colorFlor":"Morado",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"Ojos azules",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"0:29",
    "audioFin":"0:32"
  },
  {
    "numero":7,
    "nombre":"CAMOTILLO",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Camote pequeño",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Amarillo",
    "formaRara":"Oblongo alargado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"0:35",
    "audioFin":"0:38"
  },
  {
    "numero":8,
    "nombre":"CARAMELO SUYTU",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Caramelo largo",
    "colorFlor":"Blanco",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Combinado",
    "formaRara":"Oblongo alargado",
    "toleranciaHelada":"Fuerte",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"0:41",
    "audioFin":"0:44"
  },
  {
    "numero":9,
    "nombre":"CHIQCHI PASÑA",
    "nombreAlternativo":"Yuraq Chiqchi Pasña",
    "significadoNombre":"Señorita chispeada",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco a crema",
    "formaRara":"Comprimida",
    "toleranciaHelada":"Débil",
    "usoCocina":"Watia, hervido",
    "lugar":"Huancavelica",
    "audioIni":"0:47",
    "audioFin":"0:50"
  },
  {
    "numero":10,
    "nombre":"COMPIS",
    "nombreAlternativo":"Puka Imilla",
    "significadoNombre":"(No definido)",
    "colorFlor":"Blanco",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Blanco",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"0:53",
    "audioFin":"0:56"
  },
  {
    "numero":11,
    "nombre":"CÓNDOR RUNTU",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Huevo de cóndor",
    "colorFlor":"Morado oscuro con acúmenes blancos",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco",
    "formaRara":"Ovalado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido y bonda",
    "lugar":"Cusco",
    "audioIni":"0:59",
    "audioFin":"1:01"
  },
  {
    "numero":12,
    "nombre":"CORDOVINA",
    "nombreAlternativo":"Clavelina",
    "significadoNombre":"Cordovina",
    "colorFlor":"Rojo a Morado",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"Comprimida",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"1:05",
    "audioFin":"1:07"
  },
  {
    "numero":13,
    "nombre":"DUSIS",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"(No definido)",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Combinado",
    "formaRara":"Oblongo",
    "toleranciaHelada":"Débil",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"1:10",
    "audioFin":"1:12"
  },
  {
    "numero":14,
    "nombre":"HUAMAN UMA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Cabeza del águila huamancha",
    "colorFlor":"Violeta",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Amarillo claro",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"1:16",
    "audioFin":"1:18"
  },
  {
    "numero":15,
    "nombre":"HUAMANTANGA",
    "nombreAlternativo":"Puka Aqu Suytu",
    "significadoNombre":"Roja arenosa larga - Huamantanga (es un pueblo)",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco a crema",
    "formaRara":"Oblongo alargado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"1:21",
    "audioFin":"1:24"
  },
  {
    "numero":16,
    "nombre":"KICHKA MATANKA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Espina en la espalda",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Combinado",
    "formaRara":"Comprimida",
    "toleranciaHelada":"Fuerte",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"1:26",
    "audioFin":"1:30"
  },
  {
    "numero":17,
    "nombre":"KUCHIPA AKAN",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Excremento de chancho",
    "colorFlor":"Morado",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Blanco",
    "formaRara":"Oblongo",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"1:33",
    "audioFin":"1:36"
  },
  {
    "numero":18,
    "nombre":"LINLIN",
    "nombreAlternativo":"Yana Linli y Moro",
    "significadoNombre":"(No definido)",
    "colorFlor":"Morado",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"1:40",
    "audioFin":"1:42"
  },
  {
    "numero":19,
    "nombre":"LLAMA SENQA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Nariz de llama",
    "colorFlor":"Violeta",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco",
    "formaRara":"Oblondo Alargado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido y watia",
    "lugar":"Cusco",
    "audioIni":"1:45",
    "audioFin":"1:48"
  },
  {
    "numero":20,
    "nombre":"LUNTUS (RUNTUS)",
    "nombreAlternativo":"Luntus",
    "significadoNombre":"Yema de huevo",
    "colorFlor":"Blanco",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Amarillo intenso",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"4:57",
    "audioFin":"5:00"
  },
  {
    "numero":21,
    "nombre":"MAQA SONQO",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Corazón sin sabor",
    "colorFlor":"Rosado a rojo",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Débil",
    "usoCocina":"Watia, hervido y chuño",
    "lugar":"Cusco",
    "audioIni":"1:50",
    "audioFin":"1:53"
  },
  {
    "numero":22,
    "nombre":"MARKINA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Markina",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Combinado",
    "formaRara":"Oblongo",
    "toleranciaHelada":"Fuerte",
    "usoCocina":"Watia, hervido",
    "lugar":"Huancavelica",
    "audioIni":"1:56",
    "audioFin":"1:59"
  },
  {
    "numero":23,
    "nombre":"MURU HUARILLO",
    "nombreAlternativo":"Muru Wakrillo",
    "significadoNombre":"Asta negra y blanca",
    "colorFlor":"Morado",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Blanco",
    "formaRara":"Enroscado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Chuño",
    "lugar":"Apurímac",
    "audioIni":"2:02",
    "audioFin":"2:04"
  },
  {
    "numero":24,
    "nombre":"MURU LINLIN",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Linli de blanco y negro",
    "colorFlor":"Morado",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"2:08",
    "audioFin":"2:10"
  },
  {
    "numero":25,
    "nombre":"MURU LLUMCHUY WAQACHI",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Bicolor hace llorar a la nuera",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Amarillo",
    "formaRara":"Tuberosado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"2:13",
    "audioFin":"2:17"
  },
  {
    "numero":26,
    "nombre":"MURU PHUQUYA",
    "nombreAlternativo":"Moro Phocoya",
    "significadoNombre":"",
    "colorFlor":"Rosado",
    "toleranciaGranizada":"Fuerte",
    "colorPulpa":"Blanco",
    "formaRara":"No tiene",
    "toleranciaHelada":"Fuerte",
    "usoCocina":"",
    "lugar":"Apurímac",
    "audioIni":"2:19",
    "audioFin":"2:22"
  },
  {
    "numero":27,
    "nombre":"MURU WAYRU",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Wayru bicolor",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Amarillo",
    "formaRara":"Oblongo alargado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"2:25",
    "audioFin":"2:28"
  },
  {
    "numero":28,
    "nombre":"PALTA SUSO",
    "nombreAlternativo":"Palteña",
    "significadoNombre":"Roja plana",
    "colorFlor":"Lila",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Amarillo claro",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Mondar, pelar y sopas",
    "lugar":"Apurímac",
    "audioIni":"2:31",
    "audioFin":"2:33"
  },
  {
    "numero":29,
    "nombre":"PAQUS",
    "nombreAlternativo":"Pacos",
    "significadoNombre":"(No definido)",
    "colorFlor":"Morado",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Amarillo claro",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Pelar, sopas",
    "lugar":"Apurímac",
    "audioIni":"2:36",
    "audioFin":"2:39"
  },
  {
    "numero":30,
    "nombre":"PARIWANA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Flamenco (ave)",
    "colorFlor":"Violeta",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"Obovado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido, sopas, al horno",
    "lugar":"Cusco",
    "audioIni":"2:41",
    "audioFin":"2:44"
  },
  {
    "numero":31,
    "nombre":"PAYAPA ANKUN",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Talon de Anciana",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Blanco a crema",
    "formaRara":"Oblongo",
    "toleranciaHelada":"Fuerte",
    "usoCocina":"Watia, hervido y chuño",
    "lugar":"Huancavelica",
    "audioIni":"2:46",
    "audioFin":"2:49"
  },
  {
    "numero":32,
    "nombre":"PERUANITA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Color de la bandera peruana (pequeña)",
    "colorFlor":"Rojo Morado",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Amarillo",
    "formaRara":"Oblongo",
    "toleranciaHelada":"Débil",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"2:53",
    "audioFin":"2:55"
  },
  {
    "numero":33,
    "nombre":"PRESCOS",
    "nombreAlternativo":"Bayo Botas, Qompis",
    "significadoNombre":"(No definido)",
    "colorFlor":"Blanco",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco a crema",
    "formaRara":"Redondo",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"2:58",
    "audioFin":"3:02"
  },
  {
    "numero":34,
    "nombre":"PUKA BOTIJUELA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Botijuela roja",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco o crema",
    "formaRara":"Oblongo",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"3:03",
    "audioFin":"3:06"
  },
  {
    "numero":35,
    "nombre":"PUKA CHIMAKU",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Chiwako (zorzal, tordo) rojo",
    "colorFlor":"Lila",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Crema",
    "formaRara":"Fusiforme",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido y chuño",
    "lugar":"Cusco",
    "audioIni":"3:10",
    "audioFin":"3:12"
  },
  {
    "numero":36,
    "nombre":"PUKA CHIQCHI PASÑA",
    "nombreAlternativo":"Puka Pasña",
    "significadoNombre":"Señorita roja chispeada",
    "colorFlor":"Lila a Morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco a Crema",
    "formaRara":"Comprimida",
    "toleranciaHelada":"Débil",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"3:16",
    "audioFin":"3:19"
  },
  {
    "numero":37,
    "nombre":"PUKA CHURUSPE",
    "nombreAlternativo":"Puka Churuspi",
    "significadoNombre":"Churuspi rojo",
    "colorFlor":"Rojo-morado pálido con blanco en el acumen (Envés)",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema y anillo vascular y medula roja",
    "formaRara":"Oblongo alargado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido, sopas y chuño",
    "lugar":"Cusco",
    "audioIni":"3:22",
    "audioFin":"3:25"
  },
  {
    "numero":38,
    "nombre":"PUKA INKACHU",
    "nombreAlternativo":"",
    "significadoNombre":"De los inkas, rojo",
    "colorFlor":"Rosado a rojo",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Débil",
    "usoCocina":"Hervido y watias",
    "lugar":"Cusco",
    "audioIni":"3:28",
    "audioFin":"3:31"
  },
  {
    "numero":39,
    "nombre":"PUKA ÑAWI SUYTO",
    "nombreAlternativo":"Yurac Huachala",
    "significadoNombre":"Blanco que produce bastante. Con ojos rojos",
    "colorFlor":"Violeta",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"3:33",
    "audioFin":"3:37"
  },
  {
    "numero":40,
    "nombre":"PUKA QHACHUN WAQACHI",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"La que hace llorar a la nuera, rojo",
    "colorFlor":"Rojo Morado",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"Oblongo alargado concertinada y ojos profundos.",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido, papa seca, al horno, watias",
    "lugar":"Cusco",
    "audioIni":"3:40",
    "audioFin":"3:44"
  },
  {
    "numero":41,
    "nombre":"PUKA QULLUNA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"(No definido)",
    "colorFlor":"Lila",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema/rojo (anillo angosto)",
    "formaRara":"Bastantes ojos",
    "toleranciaHelada":"Fuerte",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"3:47",
    "audioFin":"3:50"
  },
  {
    "numero":42,
    "nombre":"PUKA RUMPHU K´USI",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"CalabacÍn ovalado y rojo",
    "colorFlor":"Morado sin botones",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema con pigmentos morados",
    "formaRara":"Ovalado aplanado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Chuño, hervido, watia, chuño",
    "lugar":"Cusco",
    "audioIni":"3:53",
    "audioFin":"3:56"
  },
  {
    "numero":43,
    "nombre":"PUKA SHUALLULLA",
    "nombreAlternativo":"Huancucho Rojo",
    "significadoNombre":"Rojo ratero mentiroso",
    "colorFlor":"Lila",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Blanco",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"3:59",
    "audioFin":"4:02"
  },
  {
    "numero":44,
    "nombre":"PUKA WAYRU",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Wayru rojo",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Amarillo",
    "formaRara":"Oblongo alargado",
    "toleranciaHelada":"Débil",
    "usoCocina":"Watia, hervido",
    "lugar":"Huancavelica",
    "audioIni":"4:05",
    "audioFin":"4:08"
  },
  {
    "numero":45,
    "nombre":"PUMA MAKI",
    "nombreAlternativo":"Pumaq Makin",
    "significadoNombre":"Mano del puma",
    "colorFlor":"Violeta",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"mano u garra del puma",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Chuño",
    "lugar":"Apurímac",
    "audioIni":"4:12",
    "audioFin":"4:14"
  },
  {
    "numero":46,
    "nombre":"PUQYA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Puqya",
    "colorFlor":"Blanco",
    "toleranciaGranizada":"Fuerte",
    "colorPulpa":"Blanco a crema",
    "formaRara":"Oblongo",
    "toleranciaHelada":"Fuerte",
    "usoCocina":"Watia, hervido",
    "lugar":"Huancavelica",
    "audioIni":"4:17",
    "audioFin":"4:19"
  },
  {
    "numero":47,
    "nombre":"Q´ELLO RUNTHUS",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Huevo amarillo",
    "colorFlor":"Blanco Intermedio",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Amarillo intenso",
    "formaRara":"Comprimida",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, purés y hervido",
    "lugar":"Cusco",
    "audioIni":"4:23",
    "audioFin":"4:25"
  },
  {
    "numero":48,
    "nombre":"Q´EWILLO",
    "nombreAlternativo":"Alka Charka",
    "significadoNombre":"Serpenteante",
    "colorFlor":"Azul morado",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Crema con pigmentos morados",
    "formaRara":"Alargada",
    "toleranciaHelada":"Débil",
    "usoCocina":"Moraya, chuño",
    "lugar":"Cusco",
    "audioIni":"4:29",
    "audioFin":"4:31"
  },
  {
    "numero":49,
    "nombre":"QALAPA WARAN",
    "nombreAlternativo":"Waripa Tacllan",
    "significadoNombre":"Ropa vieja- Arado de pie de joven",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Amarillo",
    "formaRara":"Oblongo alargado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"4:34",
    "audioFin":"4:37"
  },
  {
    "numero":50,
    "nombre":"QHACHUM WAQACHI",
    "nombreAlternativo":"Chocllos",
    "significadoNombre":"Hace llorar a la yerna",
    "colorFlor":"Lila",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Amarillo",
    "formaRara":"Ojos profundos",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"4:40",
    "audioFin":"4:43"
  },
  {
    "numero":51,
    "nombre":"QULLQI TUPU",
    "nombreAlternativo":"Yuraq Peruanita",
    "significadoNombre":"Tupu (prendedor) de plata",
    "colorFlor":"Rojo a morado",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Blanco",
    "formaRara":"Oblongo",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"4:46",
    "audioFin":"4:49"
  },
  {
    "numero":52,
    "nombre":"RISCO",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"(No definido)",
    "colorFlor":"Blanco",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"4:52",
    "audioFin":"4:54"
  },
  {
    "numero":53,
    "nombre":"RUNTUS",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Huevo",
    "colorFlor":"Blanco",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Amarillo",
    "formaRara":"Redondo",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Causa, hervido",
    "lugar":"Huancavelica",
    "audioIni":"4:57",
    "audioFin":"5:00"
  },
  {
    "numero":54,
    "nombre":"SALAMANCA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"(No definido)",
    "colorFlor":"Azul celeste",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"5:03",
    "audioFin":"5:05"
  },
  {
    "numero":55,
    "nombre":"SANGRE DE TORO",
    "nombreAlternativo":"Turupa Yawar",
    "significadoNombre":"Sangre de toro",
    "colorFlor":"Rosado",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Rojo",
    "formaRara":"Redondo",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"5:08",
    "audioFin":"5:11"
  },
  {
    "numero":56,
    "nombre":"SIMPA WAÑA",
    "nombreAlternativo":"",
    "significadoNombre":"Papa amarga trenzada",
    "colorFlor":"Azul",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Blanco",
    "formaRara":"No tiene",
    "toleranciaHelada":"Fuerte",
    "usoCocina":"Moraya y chuño",
    "lugar":"Apurímac",
    "audioIni":"5:14",
    "audioFin":"5:17"
  },
  {
    "numero":57,
    "nombre":"SUNCHU PAPA",
    "nombreAlternativo":"Paspa Sunchu",
    "significadoNombre":"Papa aspera",
    "colorFlor":"Lila",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"5:20",
    "audioFin":"5:22"
  },
  {
    "numero":58,
    "nombre":"SUSO",
    "nombreAlternativo":"Puka Suso",
    "significadoNombre":"Papa sin sabor",
    "colorFlor":"Lila",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Mondar o pelar",
    "lugar":"Apurímac",
    "audioIni":"5:26",
    "audioFin":"5:28"
  },
  {
    "numero":59,
    "nombre":"SUYTU",
    "nombreAlternativo":"Yuraq Suytu",
    "significadoNombre":"Alargado",
    "colorFlor":"Rojo morado oscuro",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Blanco violeta con anillo vascular",
    "formaRara":"Elíptica",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido y bonda",
    "lugar":"Cusco",
    "audioIni":"8:10",
    "audioFin":"8:12"
  },
  {
    "numero":60,
    "nombre":"TANTAS",
    "nombreAlternativo":"Riplan",
    "significadoNombre":"Panes",
    "colorFlor":"Azul morado",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco a crema",
    "formaRara":"Oblongo",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido, sopas y guisos",
    "lugar":"Huancavelica",
    "audioIni":"5:31",
    "audioFin":"5:33"
  },
  {
    "numero":61,
    "nombre":"TRAJIN WAQACHI",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"El que hace llorar al arriero",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco a crema",
    "formaRara":"Comprimida",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"5:36",
    "audioFin":"5:39"
  },
  {
    "numero":62,
    "nombre":"UQI SUYTO",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Perro negro",
    "colorFlor":"Azul morado",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Crema",
    "formaRara":"Fusiforme alargado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido y sopas",
    "lugar":"Cusco",
    "audioIni":"5:42",
    "audioFin":"5:45"
  },
  {
    "numero":63,
    "nombre":"WAKAPA QALLUN",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Lengua de vaca",
    "colorFlor":"Rojo Morado",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco a crema",
    "formaRara":"Aplanado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"5:48",
    "audioFin":"5:51"
  },
  {
    "numero":64,
    "nombre":"WITQIS",
    "nombreAlternativo":"Sirina",
    "significadoNombre":"Wiqtis -Sirena",
    "colorFlor":"Celeste a Azul",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco a crema",
    "formaRara":"Oblongo",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"5:54",
    "audioFin":"5:57"
  },
  {
    "numero":65,
    "nombre":"YANA CHARKA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Lugar negro",
    "colorFlor":"Morado oscuro",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"Oblondo Alargado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Chuño",
    "lugar":"Cusco",
    "audioIni":"6:01",
    "audioFin":"6:03"
  },
  {
    "numero":66,
    "nombre":"YANA CHIQCHI PASÑA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Señorita negra chispeada",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco a crema",
    "formaRara":"Comprimida",
    "toleranciaHelada":"Débil",
    "usoCocina":"Watia, hervido",
    "lugar":"Huancavelica",
    "audioIni":"6:06",
    "audioFin":"6:09"
  },
  {
    "numero":67,
    "nombre":"YANA CHURUSPE",
    "nombreAlternativo":"Yana Churuspi",
    "significadoNombre":"Churuspi negro",
    "colorFlor":"Morado oscuro",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco-violeta con anillo vascular y médula",
    "formaRara":"Oblongo alargado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido y watias",
    "lugar":"Cusco",
    "audioIni":"6:12",
    "audioFin":"6:15"
  },
  {
    "numero":68,
    "nombre":"YANA GASPAR",
    "nombreAlternativo":"Yana ñata",
    "significadoNombre":"Gaspar Negro",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco a crema",
    "formaRara":"Tuberosado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"6:18",
    "audioFin":"6:21"
  },
  {
    "numero":69,
    "nombre":"YANA IMILIA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Muchacha juvenil",
    "colorFlor":"Morado",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Amarillo claro",
    "formaRara":"Comprimida",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido, chuño, watia y sopas",
    "lugar":"Cusco",
    "audioIni":"6:23",
    "audioFin":"6:27"
  },
  {
    "numero":70,
    "nombre":"YANA LINLIN",
    "nombreAlternativo":"Papa negra",
    "significadoNombre":"(No definido)",
    "colorFlor":"Morado",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Fuerte",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"6:29",
    "audioFin":"6:32"
  },
  {
    "numero":71,
    "nombre":"YANA LLUMCHUY WAQACHI",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Negra hace llorar a la nuera",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco a crema",
    "formaRara":"Tuberosado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"6:35",
    "audioFin":"6:38"
  },
  {
    "numero":72,
    "nombre":"YANA MANWA",
    "nombreAlternativo":"Manua",
    "significadoNombre":"Manwa negra",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Fuerte",
    "colorPulpa":"Combinado",
    "formaRara":"Oblongo",
    "toleranciaHelada":"Fuerte",
    "usoCocina":"Chuño y sopa",
    "lugar":"Huancavelica",
    "audioIni":"6:41",
    "audioFin":"6:44"
  },
  {
    "numero":73,
    "nombre":"YANA ÑATA",
    "nombreAlternativo":"Ñata",
    "significadoNombre":"Achatado Negro",
    "colorFlor":"Lila a Morada",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Blanco a Crema",
    "formaRara":"Comprimida",
    "toleranciaHelada":"Fuerte",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"6:47",
    "audioFin":"6:50"
  },
  {
    "numero":74,
    "nombre":"YANA ÑAWI PASÑA",
    "nombreAlternativo":"Yana Chusña",
    "significadoNombre":"Muchacha de ojos negros o azules",
    "colorFlor":"Rojo morado o morado",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"6:53",
    "audioFin":"6:56"
  },
  {
    "numero":75,
    "nombre":"YANA PUTIS",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"(No definido)",
    "colorFlor":"Morado",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema/rojo. Anillo angosto",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"6:58",
    "audioFin":"7:00"
  },
  {
    "numero":76,
    "nombre":"YANA RUMPHU K´USI",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Calabacín ovalado y negro",
    "colorFlor":"Lila pálido",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Crema con anillo vascular morado",
    "formaRara":"Ovalado aplanado",
    "toleranciaHelada":"Débil",
    "usoCocina":"Chuño, hervido, watia, chuño",
    "lugar":"Cusco",
    "audioIni":"7:03",
    "audioFin":"7:07"
  },
  {
    "numero":77,
    "nombre":"YANA SHUALLULLA",
    "nombreAlternativo":"Huancucho Negro",
    "significadoNombre":"Negro Ratero mentiroso",
    "colorFlor":"Lila",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Blanco/Morado. Anillo vascular y medalla",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"7:10",
    "audioFin":"7:13"
  },
  {
    "numero":78,
    "nombre":"YANA SUSO",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Papa sin sabor",
    "colorFlor":"Morado",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema/morado. Anillo angosto",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Mondar, pelar y sopas",
    "lugar":"Apurímac",
    "audioIni":"7:16",
    "audioFin":"7:19"
  },
  {
    "numero":79,
    "nombre":"YANA WAKCHILLA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Garza negra",
    "colorFlor":"",
    "toleranciaGranizada":"",
    "colorPulpa":"",
    "formaRara":"",
    "toleranciaHelada":"",
    "usoCocina":"",
    "lugar":"Apurímac",
    "audioIni":"7:23",
    "audioFin":"7:25"
  },
  {
    "numero":80,
    "nombre":"YANA WILLKAS",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Sagrado negro",
    "colorFlor":"Morado",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Morado",
    "formaRara":"Oblondo Alargado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Chuño, moraya",
    "lugar":"Cusco",
    "audioIni":"7:28",
    "audioFin":"7:31"
  },
  {
    "numero":81,
    "nombre":"YANA WINQU",
    "nombreAlternativo":"Winqu",
    "significadoNombre":"Negro torcido",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Combinado",
    "formaRara":"Alargada",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"7:35",
    "audioFin":"7:37"
  },
  {
    "numero":82,
    "nombre":"YURAQ INKACHU",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"De los inkas, blanco",
    "colorFlor":"Blanco pálido",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Débil",
    "usoCocina":"Hervido y watias",
    "lugar":"Cusco",
    "audioIni":"7:40",
    "audioFin":"7:44"
  },
  {
    "numero":83,
    "nombre":"YURAQ IPILLU",
    "nombreAlternativo":"Yuraq Culebrina",
    "significadoNombre":"Ipillu blanco",
    "colorFlor":"Rojo Morado",
    "toleranciaGranizada":"Débil",
    "colorPulpa":"Blanco a Crema",
    "formaRara":"Alargada",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Chuño",
    "lugar":"Huancavelica",
    "audioIni":"7:47",
    "audioFin":"7:50"
  },
  {
    "numero":84,
    "nombre":"YURAQ MAKO",
    "nombreAlternativo":"Maco",
    "significadoNombre":"Maco blanco",
    "colorFlor":"Lila a morada",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Blanco a crema",
    "formaRara":"Oblongo",
    "toleranciaHelada":"Fuerte",
    "usoCocina":"Hervido",
    "lugar":"Huancavelica",
    "audioIni":"7:51",
    "audioFin":"7:53"
  },
  {
    "numero":85,
    "nombre":"YURAQ SOLE",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Sole blanco",
    "colorFlor":"Lila oscura",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Rojo con corteza blanca",
    "formaRara":"Oblondo Obovado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido y chuño",
    "lugar":"Cusco",
    "audioIni":"7:57",
    "audioFin":"7:59"
  },
  {
    "numero":86,
    "nombre":"YURAQ SUNCHUS",
    "nombreAlternativo":"Paspa Sunchu",
    "significadoNombre":"Papa áspera",
    "colorFlor":"Lila",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Mondar, pelar y sopas",
    "lugar":"Apurímac",
    "audioIni":"8:03",
    "audioFin":"8:05"
  },
  {
    "numero":87,
    "nombre":"YURAQ SUYTO",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Blanco alargado",
    "colorFlor":"Lila",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"8:09",
    "audioFin":"8:12"
  },
  {
    "numero":88,
    "nombre":"YURAQ WACHALLA",
    "nombreAlternativo":"Puka Ñawi Wachala",
    "significadoNombre":"Blanco que produce bastante",
    "colorFlor":"Violeta",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Crema",
    "formaRara":"No tiene",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Watia, hervido",
    "lugar":"Apurímac",
    "audioIni":"8:14",
    "audioFin":"8:17"
  },
  {
    "numero":89,
    "nombre":"YURAQ WAÑA",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Papa amarga",
    "colorFlor":"Morado",
    "toleranciaGranizada":"Fuerte",
    "colorPulpa":"Blanco",
    "formaRara":"No tiene",
    "toleranciaHelada":"Fuerte",
    "usoCocina":"Chuño y moraya",
    "lugar":"Apurímac",
    "audioIni":"8:21",
    "audioFin":"8:23"
  },
  {
    "numero":90,
    "nombre":"YURAQ WILLKAS",
    "nombreAlternativo":"No tiene",
    "significadoNombre":"Sagrado blanco",
    "colorFlor":"Lila oscura",
    "toleranciaGranizada":"Intermedio",
    "colorPulpa":"Amarillo",
    "formaRara":"Obovado",
    "toleranciaHelada":"Intermedio",
    "usoCocina":"Hervido, chuño, bonda y sopas",
    "lugar":"Cusco",
    "audioIni":"8:26",
    "audioFin":"8:28"
  }
];
